pull_request_rules:

  - name: label ovo-scala-steward's failed PRs
    conditions:
      - author=ovo-scala-steward
      - status-failure~=ci/circleci
    actions:
      label:
        add:
          - ovo-scala-steward
          - failed-update

  - name: label ovo-scala-steward's major version PRs
    conditions:
      - author=ovo-scala-steward
      - body~=labels:.*semver-major
    actions:
      label:
        add:
          - ovo-scala-steward
          - major-update

  - name: automatically merge ovo-scala-steward's minor version PRs
    conditions:
      - author=ovo-scala-steward
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: integration_test"
      - "status-success=ci/circleci: unit_test"
      - body~=labels:.*semver-minor
    actions:
      review:
        type: APPROVE
      merge:
        strict: smart
        strict_method: rebase
        method: merge
      label:
        add:
          - ovo-scala-steward
          - minor-update
        remove:
          - failed-update
      delete_head_branch: {}

  - name: automatically merge ovo-scala-steward's patch version PRs
    conditions:
      - author=ovo-scala-steward
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: integration_test"
      - "status-success=ci/circleci: unit_test"
      - body~=labels:.*semver-patch
    actions:
      review:
        type: APPROVE
      merge:
        strict: smart
        strict_method: rebase
        method: merge
      label:
        add:
          - ovo-scala-steward
          - patch-update
        remove:
          - failed-update
      delete_head_branch: {}
