pull_request_rules:

  - name: assign and label scala-steward's failed PRs
    conditions:
      - author=scala-steward
      - status-failure~=ci/circleci
    actions:
      assign:
        users: ["@ovotech/comms"]
      label:
        add: [ovo-scala-steward, failed-update]

  - name: assign and label scala-steward's major version PRs
    conditions:
      - author=ovo-scala-steward
      - body~=labels:.*semver-major
    actions:
      assign:
        users: ["@ovotech/comms"]
      label:
        add: [ovo-scala-steward, major-version-update]

  - name: automatically merge scala-steward's minor version PRs
    conditions:
      - author=ovo-scala-steward
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: integration_test"
      - "status-success=ci/circleci: unit_test"
      - body~=labels:.*semver-minor
    actions:
      merge:
        method: merge
      label:
        add: [ovo-scala-steward, minor-version]

  - name: automatically merge scala-steward's patch version PRs
    conditions:
      - author=ovo-scala-steward
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: integration_test"
      - "status-success=ci/circleci: unit_test"
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: merge
      label:
        add: [ovo-scala-steward, patch-version]

  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
